profiles:
  SHORT:
    min_path_difficulty_ratio: 0.10
    max_path_difficulty_ratio: 0.30
    learning_generations: 500
    population_size: 512
    max_simulation_steps: 200
    target_hold_frames: 1
    elitism_ratio: 0.35
    mutation_rate: 0.45
    mutation_scale: 0.18
    lost_hp_score_impact_ratio: 0.0
